nmMode: hardlinks-local

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  "@vitejs/plugin-react@*":
    dependencies:
      vite: "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"
  "eslint-plugin-jest-dom@*":
    dependencies:
      "@testing-library/dom": "*"
  # No matching package in the dependency tree; you may not need this rule anymore.
  # eslint-plugin-i@*: 
  #   dependencies:
  #     "@typescript-eslint/parser": "*"
  #     eslint-import-resolver-typescript: "*"