nmMode: hardlinks-local

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  "@vitejs/plugin-react@*":
    dependencies:
      vite: "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": "*"
  "eslint-plugin-jest-dom@*":
    dependencies:
      "@testing-library/dom": "*"
  "berry@*": # frontend 레포에서 next config를 인식하지 못 해서 필요
    dependencies:
      "next": "*"
  "vite-tsconfig-paths@*": # frontend 레포에 vite가 없음
    dependencies:
      "vite": "*"