nmMode: hardlinks-local

nodeLinker: pnp

packageExtensions:
    '@testing-library/user-event@*':
        dependencies:
            '@testing-library/dom': '*'
    '@vitejs/plugin-react@*':
        dependencies:
            vite: '*'
    berry@*:
        dependencies:
            next: '*'
    eslint-config-next@*:
        dependencies:
            next: '*'
            react: '*'
            react-dom: '*'
    eslint-config-react-app@*:
        dependencies:
            '@babel/plugin-syntax-flow': '*'
            '@babel/plugin-transform-react-jsx': '*'
    eslint-plugin-jest-dom@*:
        dependencies:
            '@testing-library/dom': '*'
    local-pkg@*:
        dependencies:
            jsdom: '*'
    vite-tsconfig-paths@*:
        dependencies:
            vite: '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs
