# 서버에 미리 nvm이 설치되어 있어야 한다.
# https://github.com/nvm-sh/nvm
# Node 16만 가능한 환경
name: CD for frontend

on:
    workflow_dispatch:
    workflow_run:
        workflows: ['CI for frontend']
        types:
            - completed

jobs:
    CD:
        # CI 가 실패해도 completed여서, success 체크를 해줘야 함
        # https://stackoverflow.com/a/64733705
        if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Node.js 배포
              uses: appleboy/ssh-action@v1.0.0
              env:
                  NEXT_PUBLIC_API_MOCKING: true,
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              with:
                  host: ${{ secrets.DEV_SERVER_HOST }}
                  username: ${{ secrets.DEV_SERVER_USERNAME }}
                  key: ${{ secrets.DEV_SERVER_KEY }}
                  port: ${{ secrets.DEV_SERVER_PORT }}
                  envs: NEXT_PUBLIC_API_MOCKING, SENTRY_AUTH_TOKEN
                  script_stop: true
                  script: |
                      read -d '' deploy_frontend_script_env << EOF

                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh

                      nvm install 16
                      nvm use 16

                      cd ~
                      EOF

                  #   # 최초 여부에 따라 분기
                  #   # 폴더가 없으면 clone 해야 하고, 있으면 pull 해야 함
                  #   DIR="~/mono2"
                  #   if [ -d "$DIR" ]; then

                  #     # nohup으로 실행한 프로세스를 종료하기
                  #     # true를 반환해 shell이 종료되지 않음. 이 옵션은 /bin/sh -e 옵션을 줘서 테스트할 수 있음
                  #     kill -9 `cat program.pid` || true

                  #     # git fetch -all 과 동일
                  #     git remote update

                  #     # 먼저 기존 branch를 제거함. 제거하기 위해선 다른 branch에 있어야 함.
                  #     git checkout main
                  #     git branch -d ${{ github.head_ref || github.ref_name }} || true

                  #     # switch -c, checkout -b, checkout -t 모두 이미 있는 경우 오류가 발생함
                  #     git checkout -b ${{ github.head_ref || github.ref_name }} origin/${{ github.head_ref || github.ref_name }}

                  #     git pull

                  #   else

                  #     npm install -g yarn
                  #     git clone https://${{ secrets.GIT_CLONE_TOKEN }}@${{ github.server_url }}/${{ github.repository }}.git

                  #   fi

                  #   cd $DIR
                  #   yarn
                  #   yarn f build

                  #   # nohup으로 실행해 종료되지 않게
                  #   # https://stackoverflow.com/a/11856575
                  #   rm nohup.out
                  #   nohup yarn f start > nohup.out 2>&1 & echo $! > program.pid

                  # EOF
                  #   echo "$deploy_frontend_script_env" > ./deploy_frontend.sh
                  #   chmod 700 ./deploy_frontend.sh
                  #   ./deploy_frontend.sh
