# 서버에 미리 nvm이 설치되어 있어야 한다.
# https://github.com/nvm-sh/nvm
# Node 16만 가능한 환경
name: CD for frontend

on:
    workflow_dispatch:
    workflow_run:
        workflows: ['CI for frontend']
        types:
            - completed

jobs:
    CD:
        # CI 가 실패해도 completed여서, success 체크를 해줘야 함
        # https://stackoverflow.com/a/64733705
        if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Node.js 배포
              uses: appleboy/ssh-action@v1.0.0
              env:
                  NEXT_PUBLIC_API_MOCKING: true,
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              with:
                  host: ${{ secrets.DEV_SERVER_HOST }}
                  username: ${{ secrets.DEV_SERVER_USERNAME }}
                  key: ${{ secrets.DEV_SERVER_KEY }}
                  port: ${{ secrets.DEV_SERVER_PORT }}
                  envs: NEXT_PUBLIC_API_MOCKING, SENTRY_AUTH_TOKEN
                  script_stop: true
                  script: |
                      rm -f ./deploy_frontend.sh

                      # 스크립트 생성 시작
                      SCRIPT="$(pwd)/deploy_frontend.sh"
                      touch ./deploy_frontend.sh

                      # nvm PATH 설정
                      echo "export NVM_DIR=~/.nvm" >> SCRIPT
                      echo "source ~/.nvm/nvm.sh" >> SCRIPT

                      echo "nvm install 16" >> SCRIPT
                      echo "nvm use 16" >> SCRIPT

                      echo "cd ~" >> SCRIPT

                      # 최초 여부에 따라 분기
                      # 폴더가 없으면 clone 해야 하고, 있으면 pull 해야 함
                      echo "DIR=\"~/${{ github.repository }}\"" >> SCRIPT
                      echo "if [ -d \"$DIR\" ]; then" >> SCRIPT

                        # nohup으로 실행한 프로세스를 종료하기
                        # true를 반환해 shell이 종료되지 않음. 이 옵션은 /bin/sh -e 옵션을 줘서 테스트할 수 있음
                        echo "kill -9 `cat program.pid` || true" >> SCRIPT

                        # git fetch -all 과 동일
                        echo "git remote update" >> SCRIPT

                        # 먼저 기존 branch를 제거함. 제거하기 위해선 다른 branch에 있어야 함.
                        echo "git checkout main" >> SCRIPT
                        echo "git branch -d ${{ github.head_ref || github.ref_name }} || true" >> SCRIPT

                        # switch -c, checkout -b, checkout -t 모두 이미 있는 경우 오류가 발생함
                        echo "git checkout -b ${{ github.head_ref || github.ref_name }} origin/${{ github.head_ref || github.ref_name }}" >> SCRIPT
                        
                        echo "git pull" >> SCRIPT

                        echo "else" >> SCRIPT

                        echo "npm install -g yarn" >> SCRIPT
                        echo "git clone https://${{ secrets.GIT_CLONE_TOKEN }}@${{ github.server_url }}/${{ github.repository }}.git" >> SCRIPT

                        echo "fi" >> SCRIPT

                      echo "cd $DIR" >> SCRIPT
                      echo "yarn" >> SCRIPT
                      echo "yarn f build" >> SCRIPT

                      # nohup으로 실행해 종료되지 않게
                      # https://stackoverflow.com/a/11856575
                      echo "rm -f nohup.out" >> SCRIPT
                      echo "nohup yarn f start > nohup.out 2>&1 & echo $! > program.pid" >> SCRIPT

                      chmod 700 ./deploy_frontend.sh
                      cat ./deploy_frontend.sh
                      ./deploy_frontend.sh
