name: CI for api

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths: 'api/**'

jobs:
    CI:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}

            - run: echo DATABASE = $DATABASE_URL
            - run: yarn install
            - run: yarn a prisma:generate # generate는 형상 관리 대상이 아님
            - run: yarn a lint
            - run: yarn a prisma:format
            - run: yarn a test
            - run: yarn a build
