name: CI for frontend

on:
    push:
        branches: [main]
        paths: 'frontend/**'

jobs:
    CI:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - run: yarn install
            - run: yarn f dlx playwright install --with-deps # playwright 의존성 따로 설치
            - run: yarn f lint
            - run: yarn f test
            - run: yarn f test:e2e
            - run: yarn f build

            - uses: actions/upload-artifact@v3
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
